### ISSUE TITLE
Warning: EM oscillating between two states, taking the best cost solution...

### ISSUE THREAD

**Issue by vrodriguezf** [mast-group/sequence-mining#4]
Hi,

I am executing ISM with the default arguments with this input dataset:
[link to input file](https://drive.google.com/file/d/1VYW4UUnxITbrshvQfSTMWYnCpyiXJpyP/view?usp=sharing)

Setting the Log Level to WARNING, I can see that for every iteration, I get the message `EM oscillating between three states, taking best cost solution...`, and at the end, the program finishes with the warning `EM iteration limit exceeded.`

What does this mean? What can I do to make the algorithm converge?

Many thanks in advance!

**Comment by jfowkes** [comment]
Due to the way ISM works, that is we maximize a submodular multiset function to infer the best compressing sequences, EM is no longer guaranteed to converge (in particular since the submodular multiset function is non-monotone - see p.4 of the paper for details). As a result, EM can sometimes oscillate between states (we don't see this very often in practice). When ISM detects this is happening, it issues a warning and selects the best of these states as the solution. 

The `EM iteration limit exceeded` warning is unrelated and simply means the iteration limit for the ISM algorithm has been reached (this is very common as it is impossible to find all possible compressing sequences in a reasonable amount of time). I should probably change this second warning to make that clearer.

**Comment by vrodriguezf** [comment]
Thank you for your reply. 

So, if the EM oscillation happens to me almost in every iteration, taht's not usual at all, right?

**Comment by jfowkes** [comment]
I haven't encountered that before I don't think, so that is unusual yes. Are you getting sensible interesting sequences at the end?

**Comment by jfowkes** [comment]
The other thing I would suggest if you're willing to do some minor coding, would be to try PAM, our other sequence mining algorithm that we used for mining API sequences. You should be able to run `PAMCore.mineInterestingSequences` on the sequence database in the same way as ISM (see https://github.com/mast-group/api-mining/tree/master/api-miner/src/main/java/apimining/pam) but note that the main `PAM` class is set up to read in API sequences. PAM uses a slightly different algorithm that does not suffer from the EM oscillation issue, although the mined sequences may not be as good.

**Comment by vrodriguezf** [comment]
Alright, I will try that, thank you so much!!
